#!/usr/bin/env bash
# =============================================================================
# setup_network.sh — автонастройка сети для PC ↔ Jetson Nano (robot_control_v3)
# =============================================================================
#
# Использование:
#   sudo ./setup_network.sh pc          # на PC (192.168.10.1)
#   sudo ./setup_network.sh jetson      # на Jetson (192.168.10.2)
#
# Что делает:
#   1. Копирует netplan конфиг и применяет (статический IP)
#   2. Открывает порты DDS в UFW (7400-7500/udp)
#   3. Готовит fastdds_profile.xml с правильным IP
#   4. Создаёт env файл с правильным DOMAIN_ID/RMW
#
# Запускать с sudo!
# =============================================================================

set -e

ROLE="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$EUID" -ne 0 ]]; then
    echo "ERROR: запусти с sudo" >&2
    exit 1
fi

if [[ "$ROLE" != "pc" && "$ROLE" != "jetson" ]]; then
    echo "Usage: sudo $0 {pc|jetson}" >&2
    exit 1
fi

# ── Параметры в зависимости от роли ──────────────────────────────────────────
if [[ "$ROLE" == "pc" ]]; then
    HOST_IP="192.168.10.1"
    NETPLAN_SRC="$SCRIPT_DIR/netplan-pc.yaml"
    PEER_IP="192.168.10.2"
    PEER_NAME="Jetson"
else
    HOST_IP="192.168.10.2"
    NETPLAN_SRC="$SCRIPT_DIR/netplan-jetson.yaml"
    PEER_IP="192.168.10.1"
    PEER_NAME="PC"
fi

echo "==============================================================="
echo "  Setting up network for ROLE=$ROLE"
echo "  This host:  $HOST_IP"
echo "  Peer:       $PEER_IP ($PEER_NAME)"
echo "==============================================================="

# ── Шаг 1: Netplan ───────────────────────────────────────────────────────────
echo ""
echo "[1/4] Applying netplan config..."
NETPLAN_DST="/etc/netplan/01-rover-eth.yaml"

if [[ -f "$NETPLAN_DST" ]]; then
    BACKUP="${NETPLAN_DST}.bak.$(date +%s)"
    echo "  Backup existing: $BACKUP"
    cp "$NETPLAN_DST" "$BACKUP"
fi
cp "$NETPLAN_SRC" "$NETPLAN_DST"
chmod 600 "$NETPLAN_DST"

if [[ "$ROLE" == "jetson" ]]; then
    echo "  ⚠ Edit $NETPLAN_DST and set your WiFi SSID/password before applying!"
    echo "  Press ENTER to continue (or Ctrl+C to edit first)..."
    read -r
fi

netplan apply
echo "  ✓ netplan applied"

# ── Шаг 2: UFW (firewall) ────────────────────────────────────────────────────
echo ""
echo "[2/4] Opening DDS ports in UFW..."
if command -v ufw >/dev/null 2>&1; then
    ufw allow 7400:7500/udp comment "ROS2 DDS Discovery + Data" || true
    ufw allow 7400:7500/tcp comment "ROS2 DDS TCP fallback" || true
    ufw allow from 192.168.10.0/24 comment "Rover subnet" || true
    if [[ "$ROLE" == "pc" ]]; then
        ufw allow 22/tcp comment "SSH from rover/lan" || true
    fi
    echo "  ✓ ports opened"
else
    echo "  ufw not installed, skipping (please open 7400:7500/udp manually)"
fi

# ── Шаг 3: FastDDS profile с подставленным IP ────────────────────────────────
echo ""
echo "[3/4] Generating fastdds_profile.xml with HOST_IP=$HOST_IP..."
GEN_DIR="/etc/rover"
mkdir -p "$GEN_DIR"
sed "s|__HOST_IP__|$HOST_IP|g" "$SCRIPT_DIR/fastdds_profile.xml" > "$GEN_DIR/fastdds_profile.xml"
chmod 644 "$GEN_DIR/fastdds_profile.xml"
echo "  ✓ generated $GEN_DIR/fastdds_profile.xml"

# ── Шаг 4: env файл ──────────────────────────────────────────────────────────
echo ""
echo "[4/4] Generating env file..."
ENV_FILE="$GEN_DIR/env.sh"
cat > "$ENV_FILE" <<EOF
# ROS2 environment for $ROLE (auto-generated by setup_network.sh)
export ROS_DOMAIN_ID=42
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=$GEN_DIR/fastdds_profile.xml
export ROS_LOCALHOST_ONLY=0
EOF
chmod 644 "$ENV_FILE"
echo "  ✓ generated $ENV_FILE"

# ── Финальная проверка ───────────────────────────────────────────────────────
echo ""
echo "==============================================================="
echo "  Setup complete!"
echo "==============================================================="
echo ""
echo "Next steps:"
echo ""
echo "  1. Add to your ~/.bashrc:"
echo "       source $ENV_FILE"
echo ""
echo "  2. Verify connectivity to peer:"
echo "       ping -c 3 $PEER_IP"
echo ""
echo "  3. After both PC and Jetson are configured:"
echo "       ros2 topic list   # should show topics from both hosts"
echo ""

if ip addr show | grep -q "$HOST_IP"; then
    echo "✓ This host has IP $HOST_IP"
else
    echo "⚠ WARNING: $HOST_IP not assigned yet. Try: sudo netplan apply"
    echo "  Or check eth0 interface name with: ip link"
fi
echo ""
